export const BASE_URL = "https://gstatic.97kid.com/sui/stone/";

export const IMAGE_LIST: { [key in string]: string[] } = {
  earringimageUrl: ["1.gif", "2.png", "3.png", "4.png", "5.png", "6.png"],
  head: [
    "1.png",
    "2.gif",
    "3.png",
    "4.png",
    "5.png",
    "6.gif",
    "7.gif",
    "8.png",
    "9.gif",
    "10.gif",
  ],
  necklace: ["1.png", "2.png", "3.png", "4.png", "5.png", "6.png", "7.png"],
  clothes: [
    "1.png",
    "2.png",
    "3.png",
    "4.png",
    "5.png",
    "6.png",
    "7.gif",
    "8.png",
    "9.gif",
    "10.png",
  ],
  mouth: [
    "1.gif",
    "2.png",
    "3.png",
    "4.gif",
    "5.gif",
    "6.gif",
    "7.gif",
    "8.gif",
    "9.gif",
    "10.gif",
  ],
  background: [
    "1.png",
    "2.png",
    "3.png",
    "4.png",
    "5.png",
    "6.png",
    "7.png",
    "8.png",
    "9.png",
    "10.png",
  ],
  body: [
    "1.gif",
    "2.gif",
    "3.gif",
    "4.gif",
    "5.gif",
    "6.gif",
    "7.gif",
    "8.gif",
    "9.gif",
    "10.gif",
  ],
  glass: [
    "1.gif",
    "2.gif",
    "3.gif",
    "4.png",
    "5.gif",
    "6.png",
    "7.gif",
    "8.gif",
    "9.gif",
    "10.png",
  ],
};
